version: '3.5'
services:
  db-dev:
    image: postgres:latest
    container_name: db-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend-dev:
    build: .
    container_name: backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db-dev

volumes:
  postgres_data:
