"""create_user_models

Revision ID: cecd88cc07aa
Revises: 
Create Date: 2023-09-01 17:54:31.239306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cecd88cc07aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS user_role_enum;")
    op.execute(
        "CREATE TYPE user_role_enum as ENUM('worker', 'customer');"
    )
    op.create_table('users',
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('username', sa.String(length=255), nullable=True),
                    sa.Column('role', postgresql.ENUM('worker', 'customer', name='user_role_enum', create_type=False), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS user_role_enum;")
    # ### end Alembic commands ###
